# PiggyCustomEnchants Configuration File v1.0

# Enchant Rarity Color Customization
# List of available colors:
# black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, and white.
color:
  common: yellow
  uncommon: blue
  rare: green
  mythical: purple