# Specifies the color enchants are shown depending on rarity.
# Options: black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, and white.
rarity-colors:
  common: yellow
  uncommon: blue
  rare: gold
  mythic: light_purple
enchants:
  # Specifies the location enchants are shown. Options: name, lore
  position: "name"
  # Toggles roman numerals for displaying enchantment levels
  roman-numerals: true
# Toggles forms for /ce command
forms:
  enabled: false
# What enchants to disable ENTIRELY
disabled-enchants: []
# What enchants to disable in specific worlds
per-world-disabled-enchants:
  NoJetpackWorld:
    - "jetpack"
# If enabled, will check https://gist.github.com/DaPigGuy/9c65a998bc0aa8d6b4708796110f7d11 for extremely problematic enchantments on your version of the plugin to be disabled
remote-disable: true
# Whether or not an enchant damages world
world-damage:
  blaze: true
  bombardment: true
  lightning: true
  missile: true
  self-destruct: true
# Items the chicken enchant will drop. Formatted as "id:meta:count"
chicken:
  drops: ["266:0:1"]
miscellaneous:
  # Toggles PiggyCE's implementation of the vanilla feature to hold armor to equip
  armor-hold-equip: true
# Reaction chances are defined as chance multiplier x enchantment level. The chance multiplier by default for most enchantments is 100.
# Chance multipliers can be defined for any reactive enchantments. Enchantments below merely have default chance multipliers.
# Please keep enchantment names LOWERCASE
chances:
  blessed: 15
  deepwounds: 20
  disarmor: 10
  disarming: 10
  hallucination: 5
  jackpot: 10
  lightning: 10